function handle = addPanelLabel(ax, label)
%ADDPANELLABEL Place a stable lower-case panel label outside the data area.

style = phg.figureStyle;
handle = text(ax, -0.04, 1.03, string(label), 'Units', 'normalized', ...
    'FontName', style.fontName, 'FontSize', style.panelFontSize, ...
    'FontWeight', 'bold', 'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', 'Clipping', 'off', ...
    'Tag', 'phgPanelLabel');
end
