function surface = buildTransparentBrainSurface(cfg)
%BUILDTRANSPARENTBRAINSURFACE Build/cache an MNI surface from a TPM image.
% LeGUI is preferred when configured because it preserves the workflow used
% by the original laboratory localization software. A MATLAB NIfTI fallback is
% used when LeGUI/SPM functions are unavailable.

surface = struct('vertices', zeros(0,3), 'faces', zeros(0,3));
if isfile(cfg.templateSurfaceCache)
    try
        cached = load(cfg.templateSurfaceCache, 'surface');
        if isfield(cached, 'surface') && ...
                ~isempty(cached.surface.vertices) && ...
                all(isfinite(cached.surface.vertices), 'all')
            surface = cached.surface;
            return
        end
        warning('phg:InvalidSurfaceCache', ...
            'Cached brain surface is incomplete; regenerating it.');
    catch exception
        warning('phg:InvalidSurfaceCache', ...
            'Could not read cached brain surface (%s); regenerating it.', ...
            exception.message);
    end
end

tpmFile = string(cfg.templateTpmFile);
if tpmFile == "" && isfield(cfg, 'leGUIRoot') && isfolder(cfg.leGUIRoot)
    candidate = fullfile(cfg.leGUIRoot, 'tpm', 'TPM.nii');
    if isfile(candidate)
        tpmFile = candidate;
    end
end
if tpmFile == "" || ~isfile(tpmFile)
    warning('phg:NoBrainTemplate', ...
        ['No TPM template configured. Electrode coordinates will still be ' ...
         'plotted, but without a brain surface.']);
    return
end

usedLeGUI = false;
if isfield(cfg, 'leGUIRoot') && isfolder(cfg.leGUIRoot)
    % LeGUI is added to the path only for the duration of the call. Its bundled
    % SPM shadows several MATLAB names, so it must not be left on the path.
    addpath(cfg.leGUIRoot);
    restorePath = onCleanup(@() rmpath(cfg.leGUIRoot));
    if exist('LeG_genSurfaces', 'file') == 2
        try
            % LeG_genSurfaces itself needs only the Image Processing Toolbox.
            % The SPM dependency lives in spm_vol/spm_read_vols, whose
            % spm_slice_vol mex is not built for this platform, so the tissue
            % volumes and the voxel-to-world affine are read natively instead
            % and handed to LeGUI in the header form it expects.
            [gray, white, imgInfo] = readTissueVolumes(tpmFile);
            [surface, ~] = LeG_genSurfaces({gray, white}, imgInfo);
            usedLeGUI = true;
            fprintf(['[PHG] Brain surface generated by LeGUI ', ...
                'LeG_genSurfaces (native NIfTI reader).\n']);
        catch exception
            warning('phg:LeGUIFallback', ...
                'LeGUI surface generation failed (%s); using MATLAB fallback.', ...
                exception.message);
        end
    end
    clear restorePath
end

if ~usedLeGUI
    info = niftiinfo(tpmFile);
    probability = single(niftiread(info));
    if ndims(probability) < 4 || size(probability, 4) < 2
        error('phg:InvalidTemplate', ...
            'Expected gray and white tissue volumes in %s.', tpmFile);
    end
    tissue = sum(probability(:,:,:,1:2), 4);
    if max(tissue, [], 'all') > 2
        tissue = tissue ./ max(tissue, [], 'all');
    end
    tissue = smooth3(tissue, 'box', [3 3 3]);
    voxelSurface = isosurface(tissue, 0.35);
    intrinsic = [voxelSurface.vertices(:,2), ...
        voxelSurface.vertices(:,1), voxelSurface.vertices(:,3)];
    try
        world = transformPointsForward(info.Transform, intrinsic);
    catch
        homogeneous = [intrinsic, ones(size(intrinsic, 1), 1)] * info.Transform.T;
        world = homogeneous(:, 1:3);
    end
    surface.faces = voxelSurface.faces;
    surface.vertices = world;
end

if isempty(surface.vertices) || any(~isfinite(surface.vertices), 'all')
    error('phg:InvalidSurface', 'Generated brain surface is empty or non-finite.');
end

parent = fileparts(cfg.templateSurfaceCache);
if ~isfolder(parent)
    mkdir(parent);
end
temporaryCache = string(tempname(parent)) + ".mat";
save(temporaryCache, 'surface', '-v7');
movefile(temporaryCache, cfg.templateSurfaceCache, 'f');
fprintf('[PHG] Cached transparent-brain surface (%d vertices, source: %s).\n', ...
    size(surface.vertices, 1), ternaryString(usedLeGUI, ...
    'LeGUI LeG_genSurfaces', 'MATLAB isosurface fallback'));
end

% -------------------------------------------------------------------------
function [gray, white, imgInfo] = readTissueVolumes(tpmFile)
%READTISSUEVOLUMES Read TPM tissue classes and build an SPM-style header.
%   LeG_genSurfaces uses only ImgInfo.mat, the 4x4 voxel-to-world affine that
%   SPM defines over one-based voxel indices. MATLAB's niftiinfo returns the
%   transposed affine over zero-based indices, so the index origin is shifted
%   by one voxel before the matrix is handed over.

info = niftiinfo(tpmFile);
probability = single(niftiread(info));
if ndims(probability) < 4 || size(probability, 4) < 2
    error('phg:InvalidTemplate', ...
        'Expected gray and white tissue volumes in %s.', tpmFile);
end
gray = double(probability(:,:,:,1));
white = double(probability(:,:,:,2));

zeroBasedAffine = info.Transform.T';
oneToZeroBased = [eye(3), -ones(3,1); 0 0 0 1];
imgInfo = struct('mat', zeroBasedAffine * oneToZeroBased, ...
    'dim', size(gray), 'fname', char(tpmFile));
end

function out = ternaryString(condition, trueValue, falseValue)
if condition
    out = trueValue;
else
    out = falseValue;
end
end
