function createBidsScaffold(cfg)
%CREATEBIDSSCAFFOLD Create a non-PHI BIDS 1.11.1 staging skeleton.
% This function does not publish, upload, or validate patient data.

root = string(cfg.bidsRoot);
if ~isfolder(root)
    mkdir(root);
end

description = struct;
description.Name = cfg.datasetName;
description.BIDSVersion = cfg.bidsVersion;
description.DatasetType = 'raw';
description.License = 'n/a';
description.Authors = {'REPLACE AFTER INSTITUTIONAL REVIEW'};
description.HowToAcknowledge = [ ...
    'Cite the associated dataset descriptor and analysis manuscript.'];
phg.writeJson(fullfile(root, 'dataset_description.json'), description, true);

readme = [
    "# Private BIDS staging area" newline newline ...
    "This directory is generated by MATLAB and must not be uploaded until " ...
    "consent/IRB, de-identification, BIDS validation, and independent PHI " ...
    "review are complete." newline];
phg.writeText(fullfile(root, 'README'), readme, false);
phg.writeText(fullfile(root, 'CHANGES'), ...
    "0.0.1  Initial private scaffold." + newline, false);

participants = table(strings(0,1), strings(0,1), strings(0,1), ...
    'VariableNames', {'participant_id', 'site', 'task_group'});
participantsPath = fullfile(root, 'participants.tsv');
if ~isfile(participantsPath)
    writetable(participants, participantsPath, 'FileType', 'text', ...
        'Delimiter', '\t');
end

derivativeRoot = fullfile(root, 'derivatives', 'pupil-ieeg');
if ~isfolder(derivativeRoot)
    mkdir(derivativeRoot);
end
generatedBy = struct('Name', 'pupil-ieeg-matlab', ...
    'Version', '0.1.0', 'CodeURL', 'PENDING_PUBLIC_REPOSITORY');
derivativeDescription = struct('Name', ...
    'Pupil-iEEG analysis derivatives', 'BIDSVersion', cfg.bidsVersion, ...
    'DatasetType', 'derivative', 'GeneratedBy', generatedBy);
phg.writeJson(fullfile(derivativeRoot, 'dataset_description.json'), ...
    derivativeDescription, true);

fprintf('[PHG] BIDS staging scaffold: %s\n', char(root));
end
