function result = runPupilPrediction(data, cfg)
%RUNPUPILPREDICTION Train and evaluate participant-specific EEGNet regression.
% DATA must already be split without temporal leakage. The test set should be
% an entire held-out session/day whenever one is available.

required = ["XTrain", "TTrain", "XValidation", "TValidation", ...
    "XTest", "TTest"];
missing = required(~isfield(data, cellstr(required)));
if ~isempty(missing)
    error('phg:InvalidPredictionData', ...
        'Prediction input lacks: %s', strjoin(missing, ', '));
end
if exist('trainnet', 'file') ~= 2
    error('phg:MissingDeepLearningToolbox', ...
        'Deep Learning Toolbox with trainnet is required.');
end

nChannels = size(data.XTrain, 1);
nTime = size(data.XTrain, 2);
nTargetTime = size(data.TTrain, 1);
network = phg.buildEEGNetRegressor(nChannels, nTime, nTargetTime, ...
    'temporalFilters', cfg.prediction.temporalFilters, ...
    'depthMultiplier', cfg.prediction.depthMultiplier, ...
    'dropout', cfg.prediction.dropout);

trainingOptionsValue = trainingOptions('adam', ...
    'InitialLearnRate', cfg.prediction.initialLearnRate, ...
    'MaxEpochs', cfg.prediction.maxEpochs, ...
    'Shuffle', 'every-epoch', ...
    'ValidationData', {data.XValidation, data.TValidation}, ...
    'ValidationPatience', cfg.prediction.validationPatience, ...
    'Verbose', false, 'Plots', 'none');

trained = trainnet(data.XTrain, data.TTrain, network, ...
    @phg.pupilSequenceLoss, trainingOptionsValue);
prediction = minibatchpredict(trained, data.XTest);

nTrials = size(data.TTest, 2);
spearmanR = nan(nTrials,1);
nmse = nan(nTrials,1);
for trial = 1:nTrials
    target = double(data.TTest(:,trial));
    estimate = double(prediction(:,trial));
    spearmanR(trial) = corr(target, estimate, 'Type', 'Spearman', ...
        'Rows', 'complete');
    nmse(trial) = mean((estimate-target).^2, 'omitnan') ./ ...
        (var(target, 'omitnan') + eps);
end
metrics = table((1:nTrials)', spearmanR, nmse, ...
    'VariableNames', {'trial', 'spearman_r', 'nmse'});
result = struct('network', trained, 'prediction', prediction, ...
    'metrics', metrics);
end
